### ISSUE TITLE
Where can I download the dataset?

### ISSUE THREAD

**Issue by xucao-42** [za-cheng/WildLight#1]
Hi there! Congrats for the great work!
I am trying to compare your methods in my experiments. However, I didn't find the link to download your synthetic dataset to reproduce the results. 
Also, is it possible to share your blender files for generating the synthetic data? So that I can modify the rendering setting to match my setup. 

Thanks in advance!

**Comment by za-cheng** [comment]
Hi there, thank you for your interest in wildlight!

The datasets can be downloaded with python function [download_dataset()](https://github.com/za-cheng/WildLight/blob/3e9be84562c3783f8ea9b4dfdf07aa9367121988/exp_runner.py#L150). Or you can access them in google drive with file ids listed there, e.g. https://drive.google.com/uc?id=1wDyQfYL4IKvCOuwnGW9vgr66cXNWRm4B

We did not keep blender file but instead download assets from internet and used python for loading and rendering them in blender. While we don't have any timeline for releasing rendering scripts, there are other open-source projects that do the same job (e.g. [vision_blender](https://github.com/Cartucho/vision_blender))

**Comment by xucao-42** [comment]
Thanks!

**Comment by xucao-42** [comment]
I have run your code on my synthetic data, and it works excellently!
Just FYI about some tiny issues in the code
1. missing () after detach 
https://github.com/za-cheng/WildLight/blob/3e9be84562c3783f8ea9b4dfdf07aa9367121988/models/renderer.py#L258

2.  the coordinate system in mesh extraction can be modified such that the extracted mesh is aligned with the one used for rendering 
Before:
https://github.com/za-cheng/WildLight/blob/3e9be84562c3783f8ea9b4dfdf07aa9367121988/models/renderer.py#L22
After:
`pts = torch.cat([xx.reshape(-1, 1), -zz.reshape(-1, 1), yy.reshape(-1, 1)], dim=-1)`

3. torch.inverse() throws an error on my 4090 GPU.
https://github.com/za-cheng/WildLight/blob/3e9be84562c3783f8ea9b4dfdf07aa9367121988/models/dataset.py#L149

It seems this problem is GPU-related, and I move the inverse operation to cpu using numpy as following

```
intrinsics_np = self.intrinsics_all.detach().cpu().numpy()
 intrinsics_np_inv = np.linalg.inv(intrinsics_np) 
self.intrinsics_all_inv = torch.from_numpy(intrinsics_np_inv).float().to(self.device)  # [n_images, 4, 4]
```

**Comment by za-cheng** [comment]
Nice catch, thanks!

1. It's now fixed in 94e4818
2. The misalignment is due to difference in [coordinate systems](https://github.com/za-cheng/WildLight/blob/94e48181e452f4629d29164756150b1298fd5ace/exp_runner.py#L616). Both GT mesh and exported mesh with '--mode validate_mesh' options live in object coordinate, whereas intermediate exports from "--mode train" are in world coordinates. Object-to-world transformations are defined in 'camera_sphere.npy' file. 
(Another possibility is that if you used blender for rendering your data, it automatically rotate objects by 90 degrees when importing. You'll need to zero this in order to respect the original object coordinates, see image below)
4. I didn't meet this issue on 3090. Can you please post error message here?

<img width="312" alt="image" src="https://user-images.githubusercontent.com/57708879/236612568-e68934c4-d64e-4bbd-8417-e00f0c11f89b.png">

Best,
Z

**Comment by xucao-42** [comment]
The error message was
```
Traceback (most recent call last):
  File "exp_runner.py", line 676, in <module>
    runner = Runner(args.conf, args.mode, args.case, args.is_continue, args.download_dataset)
  File "exp_runner.py", line 77, in __init__
    self.dataset = Dataset(self.conf['dataset'])
  File "/home/xucao/WildLight/models/dataset.py", line 168, in __init__
    self.intrinsics_all_inv = torch.linalg.inv(self.intrinsics_all)  # [n_images, 4, 4]
RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)`
```
[This issue ](https://github.com/facebookresearch/pytorch3d/issues/1399) suggests installing a different PyTorch version, but I didn't want to touch the environment.

I think the coordinate issue is on the blender side. I used NeRF's blender files to render the images and enabled object-to-world transformation (essentially a scaling without translation, since all my cameras already look at the origin)
In blender, it is z-axis up:
<img width="998" alt="Screen Shot 2023-05-06 at 17 32 04" src="https://user-images.githubusercontent.com/28819074/236613049-21fa2100-24ee-4bae-a840-519741acbc83.png">
After I exported the mesh  using
`bpy.ops.export_scene.obj(filepath=os.path.join(OUTPUT_DIR, "scene.obj"), use_selection=False)`

It becomes y-axis up:
<img width="508" alt="Screen Shot 2023-05-06 at 17 32 32" src="https://user-images.githubusercontent.com/28819074/236613068-7c86397a-3206-469e-8518-56c3c1dfc30d.png">
 
Overlapping the extracted mesh looks like
<img width="662" alt="Screen Shot 2023-05-06 at 17 38 24" src="https://user-images.githubusercontent.com/28819074/236613389-ff3d1f4b-6e6c-4bd0-842a-d5f23963aa29.png">

We can see the difference is a 90-degree rotation about the x-axis. But this is still different from the blender rotation. 
<img width="1142" alt="Screen Shot 2023-05-06 at 17 41 22" src="https://user-images.githubusercontent.com/28819074/236613501-65d253e1-e88d-44a8-8307-66fbdd3ca99f.png">

Anyway, this is not a big problem, thanks for the information!

**Comment by za-cheng** [comment]
Thanks for the info I've now moved matrix inversion to CPU side in e6c854c.
