### ISSUE TITLE
Questions about the implementation of Disney BRDF

### ISSUE THREAD

**Issue by yxuhan** [za-cheng/WildLight#2]
Hi, thanks for your code! I have some questions about the implementation of Disney BRDF.

1. About the diffuse term:

https://github.com/za-cheng/WildLight/blob/e6c854c52e15e975e7766f8d51ca93ac68a6842d/models/physicalshader.py#L113

From the [SIGGRAPH course note](https://media.disneyanimation.com/uploads/production/publication_asset/48/asset/s2012_pbs_disney_brdf_notes_v3.pdf) (Sec. 5.3), I think it should be `(1-hz)**5` for the co-located setup. Is there a typo in the code?

2. About the geometry term:

https://github.com/za-cheng/WildLight/blob/e6c854c52e15e975e7766f8d51ca93ac68a6842d/models/physicalshader.py#L99

I read through the SIGGRAPH course note but cannot figure out the reason why the geometry term can be implemented like that. Can you explain more about the equation of the geometry term?

Thanks!

**Comment by za-cheng** [comment]
Hi there,

Thanks for your interest in wildlight. 

(1) thanks for catching this bug, it's now fixed in 86bd360
(2) this is derived from GGX distribution. A detailed treatment can be found in Section 5.3, "Understanding the Masking-Shadowing Function in Microfacet-Based BRDFs" by Heitz.

**Comment by yxuhan** [comment]
Got it. Thanks for your quick reply.

**Comment by yxuhan** [comment]
A question about the implementation of the G term. 

It seems that when calculating D and G, both alpha is defined as `roughness ** 2`.

https://github.com/za-cheng/WildLight/blob/86bd3600220f54a1f354badc8c979425051b18d7/models/physicalshader.py#L95-L101

From the [SIGGRAPH course note](https://media.disneyanimation.com/uploads/production/publication_asset/48/asset/s2012_pbs_disney_brdf_notes_v3.pdf) (Sec. 5.6), I think the code should be:

```
def _GGX_smith_for_G(hz, roughness, epsilon=1e-10):
    # here, roughness is the network's output, in range [0,1] after sigmoid
    hz_sq = hz**2
    alpha = ((roughness + 1) / 2) ** 2
    alpha_sq = alpha**2
    G = 2 / ( torch.sqrt(1 + roughness_sq * (1/hz_sq - 1)) + 1)
    return G

def _GGX_smith_for_D(hz, roughness, epsilon=1e-10):
    # here, roughness is the network's output, in range [0,1] after sigmoid
    hz_sq = hz**2
    alpha = roughness ** 2
    alpha_sq = alpha**2
    D = alpha_sq / pi / (hz_sq * (alpha_sq-1) + 1 + epsilon)**2
    return D
```

The difference between the above code and the implementation of WildLight is the way to compute alpha in G.

BTW, I think this minor issue would not affect the results to some extent.

**Comment by za-cheng** [comment]
These are very good questions. This is a short answer:

(1) ~~Burley used the mapping alpha=roughness**2 primarily because directly using roughness would be biased towards rough materials and that's not very intuitive to human artists. We left out this mapping for the same reason: we want the network to be biased to diffuse, at least at the start of training it's more stable.~~ [Edit: disregard this, see below]
(2) The mapping of alpha = ((roughness + 1) / 2) ** 2 in Walter's G creates an intuitive parameterisation that's more friendly to human artists. This however is not necessarily physically-accurate (cf Heitz, weak white-furnace test), hence we stick to the vanilla G for GGX.

**Comment by yxuhan** [comment]
Thanks for your quick reply! 
For (1), I find in the WildLight code, the mapping of alpha=roughness**2 is adopted. Did I miss something?

https://github.com/za-cheng/WildLight/blob/86bd3600220f54a1f354badc8c979425051b18d7/models/physicalshader.py#L180-L182

https://github.com/za-cheng/WildLight/blob/86bd3600220f54a1f354badc8c979425051b18d7/models/physicalshader.py#L95-L101

The 'roughness' is squared before being sent to `_GGX_smith`.

Another question is that if the definition of alpha does not have the same meaning as the one defined in Disney BRDF, can we directly export the roughness texture map and connect it to the Principled BRDF's roughness node directly in Blender? 

Or maybe we need to manually align the meaning of the roughness before connecting it to the Principled BRDF?

**Comment by za-cheng** [comment]
Ah you're right, we did use alpha=roughness**2 in our burley shader though not in plain GGX... Apologies for the confusion. I think our roughness definition is consistent with Blender (or at least seems to be during our earlier tests).

FWIW Burley also removed the mapping alpha = ((roughness + 1) / 2)**2 in favour of Heitz's paper, see Addenda in course note.

**Comment by yxuhan** [comment]
Got it. Thanks for your help!
