### ISSUE TITLE
Bug Report: Exporting all gray PBR texture maps (including base_color) 

### ISSUE THREAD

**Issue by costrice** [za-cheng/WildLight#3]
Hello, I am trying this code on my generated synthetic dataset (you can download it [here](https://drive.google.com/file/d/1qZZhV8R3GTX_iHup_lPf93Db-5UTExor/view?usp=drive_link)), with some input images shown here:
<img src="https://github.com/za-cheng/WildLight/assets/18159852/2361a34b-abf6-4f1c-b7db-4edc4210cd0d" width="256"> <img src="https://github.com/za-cheng/WildLight/assets/18159852/26a27b74-de2e-44dc-a00e-3fb3029ff085" width="256"> <img src="https://github.com/za-cheng/WildLight/assets/18159852/67e9d271-3083-4434-ad12-cf3cacd9c79d" width="256">

After training with the config `synthetic_maskless.conf` for 1,000,000 iterations using the command 
`python exp_runner.py --case synthetic_car --conf confs/synthetic_maskless.conf --mode train`,
the output validation images in `exp\car\nomask\validations_fine` seem totally fine:
<img src="https://github.com/za-cheng/WildLight/assets/18159852/1b358eaa-5af0-473c-b2bb-6469144083d9" width="256"> <img src="https://github.com/za-cheng/WildLight/assets/18159852/bdced29e-d6c4-4991-a83f-2c27901932e8" width="256">

However, when exporting the model to mesh using command 
`python exp_runner.py --case synthetic_car --conf confs/synthetic_maskless.conf --mode validate_mesh --is_continue`,
the exported uv texture maps seem broken, generating all gray PBR texture maps including base_color:
<img src="https://github.com/za-cheng/WildLight/assets/18159852/07ca7f64-0e91-4ee3-a9c6-5b2e2e4dc078" width="512">
Base color is as follows. Only a little pertubation can be seen, and most pixel values are near 128.
<img src="https://github.com/za-cheng/WildLight/assets/18159852/ee6ee971-e263-4a95-9d5f-0623f96ee346" width="512">
And [here](https://drive.google.com/file/d/1yL1j6-wx0s5--X9pGGBMjYgv2c77qJ1R/view?usp=sharing) is the checkpoint file after training for 1,000,000 iters.

It seems like a bug occurs, but I failed to find something wrong inspecting the code myself.
Could the developers check if there is something wrong? Thanks!

**Comment by za-cheng** [comment]
Hi, thanks for sharing your data and results. It looks like the flashlight intensities in the npz file don't match actual images. E.g. it looks like 000.png and 002.png are under flashlight and 001.png and 003.png aren't, however camera_sphere.npz is saying otherwise.

**Comment by costrice** [comment]
> Hi, thanks for sharing your data and results. It looks like the flashlight intensities in the npz file don't match actual images. E.g. it looks like 000.png and 002.png are under flashlight and 001.png and 003.png aren't, however camera_sphere.npz is saying otherwise.

Thanks for you answer, and I apologize for any inconvinence caused by my neglect! I am really sorry.
I will correct this problem in my .npz file and retry the code.

**Comment by costrice** [comment]
The results seem reasonable now, thanks again for the support! 
By the way, the input image, no matter provided in .png or .exr format, should be in the linear space instead of sRGB space, right? Some minor issues may have happened because of the color space I used (which is sRGB) in the input .png files.

**Comment by za-cheng** [comment]
Glad it worked out. Yes all images are expected to be equally proportional to scene radiance.
