### ISSUE TITLE
[Question] Is there any script to compute quantitative results under novel lighting, like Table 2 in the paper?

### ISSUE THREAD

**Issue by costrice** [za-cheng/WildLight#6]
Hello, I want to know if there is a script to test the trained model under given novel lighting and view point?

As far as I know, this method itself does not relight the input object under novel lighting, so we need to export mesh first, import the mesh and materials into render engines like Blender, import the target lighting into Blender, and render the mesh.
Is there any script to help generating the results under novel lighting and compute the error, so I can produce a Table like Table 2 below in the paper? 
![图片](https://github.com/za-cheng/WildLight/assets/18159852/6b0bed61-e1b8-4852-ad60-ce41345d4c7f)

I would be very grateful if the authors could provide any help (e.g. their code to generate numbers in Table 2). But it is also completely understandable if the authors think it is improper to release or have no such code. 
Thanks very much!

**Comment by za-cheng** [comment]
Hi,

For table 2 we used novel flashlight but same environment lighting. To render under novel environment you would need to export obj and textures and import them in blender. We don’t have a script for that but it shouldn’t be too difficult using blenders principled bsdf node.

Best
Ziang

**Comment by costrice** [comment]
Ok, I got it. Nevertheless thanks for your quick reply!

> Hi,
> 
> For table 2 we used novel flashlight but same environment lighting. To render under novel environment you would need to export obj and textures and import them in blender. We don’t have a script for that but it shouldn’t be too difficult using blenders principled bsdf node.
> 
> Best Ziang
